name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/arquitectura-tp/arquitecturaaplicaciones_microservicios

            echo "📥 Pull latest code"
            git pull origin main

            echo "🛑 Stop containers"
            docker compose down

            echo "🔨 Rebuild ALL images"
            docker compose build --no-cache

            echo "🚀 Start containers"
            docker compose up -d